import React from 'react';
import { ShieldCheck } from 'lucide-react';
import { CONTACT_EMAIL, FREE_DAILY_MEDIA_SCANS } from '../config.js';
import './Legal.css';

export default function Terms() {
  return (
    <div className="legal-container">
      <div className="glass-card legal-card animate-fade-in">
        <div className="legal-header">
          <ShieldCheck size={28} className="logo-icon" />
          <h1>Terms of Service</h1>
          <span className="legal-updated">Last updated: August 2026</span>
        </div>

        <p>
          By using shieldAI you agree to these terms. The service is provided free of charge,
          "as is", without warranties of any kind.
        </p>

        <h2>Acceptable use</h2>
        <ul>
          <li>Upload only content you have the right to analyze.</li>
          <li>Do not use the service to harass, defame, or target individuals.</li>
          <li>Do not attempt to bypass rate limits or quotas, or disrupt the service for others.</li>
          <li>Community reports must be made in good faith; spam and abusive content will be removed.</li>
        </ul>

        <h2>Fair-use limits</h2>
        <p>
          shieldAI is free for everyone. To keep it fast and available, media scans (image, video,
          audio) are limited to {FREE_DAILY_MEDIA_SCANS} per user per day. Link scans are
          unlimited subject to normal rate limiting. Automated scraping of the API is not permitted.
        </p>

        <h2>No warranty</h2>
        <p>
          Scan results are heuristic indicators generated by automated analysis
          (error-level analysis, lexical URL checks, prosody statistics). They are not proof of
          authenticity or tampering, and must not be relied upon as the sole basis for legal,
          financial, journalistic, or safety-critical decisions.
        </p>

        <h2>Moderation</h2>
        <p>
          Community-contributed reports and comments are moderated. We may hide or remove any
          content that is spam, illegal, misleading, or abusive, and may suspend accounts that
          repeatedly violate these terms.
        </p>

        <h2>Liability</h2>
        <p>
          To the maximum extent permitted by law, we are not liable for any damages arising from
          the use of, or inability to use, this service — including decisions made based on scan
          results.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms: <a className="legal-link" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
        </p>
      </div>
    </div>
  );
}
